#!/usr/bin/env python3
"""
Chat Conversation to PDF Converter
Claude chat'lerini HTML ve PDF formatına çevirir
"""

import sys
from datetime import datetime

def create_html_from_messages(messages, title="NEXUS Chat Session"):
    """
    Chat mesajlarını HTML'e çevir
    
    Args:
        messages: Liste of (role, content) tuples
        title: HTML başlığı
    """
    
    html_template = """
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            max-width: 900px;
            margin: 40px auto;
            padding: 20px;
            background: #f5f5f5;
            line-height: 1.6;
        }}
        
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        
        .header h1 {{
            margin: 0 0 10px 0;
            font-size: 32px;
        }}
        
        .header .meta {{
            opacity: 0.9;
            font-size: 14px;
        }}
        
        .message {{
            background: white;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
            page-break-inside: avoid;
        }}
        
        .message.user {{
            border-left: 4px solid #667eea;
        }}
        
        .message.assistant {{
            border-left: 4px solid #48bb78;
        }}
        
        .message-header {{
            display: flex;
            align-items: center;
            margin-bottom: 12px;
            font-weight: 600;
            color: #2d3748;
        }}
        
        .message.user .message-header::before {{
            content: "👤 ";
            margin-right: 8px;
        }}
        
        .message.assistant .message-header::before {{
            content: "🤖 ";
            margin-right: 8px;
        }}
        
        .message-content {{
            color: #2d3748;
            white-space: pre-wrap;
            word-wrap: break-word;
        }}
        
        .message-content code {{
            background: #f7fafc;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Monaco', 'Courier New', monospace;
            font-size: 13px;
            color: #e53e3e;
        }}
        
        .message-content pre {{
            background: #2d3748;
            color: #f7fafc;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
            font-family: 'Monaco', 'Courier New', monospace;
            font-size: 13px;
        }}
        
        .footer {{
            text-align: center;
            margin-top: 40px;
            padding: 20px;
            color: #718096;
            font-size: 14px;
        }}
        
        @media print {{
            body {{
                background: white;
                margin: 0;
                padding: 0;
            }}
            
            .message {{
                box-shadow: none;
                border: 1px solid #e2e8f0;
            }}
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <div class="meta">
            📅 {date}<br>
            💬 {message_count} mesaj<br>
            🔧 NEXUS Data Cleanroom Project
        </div>
    </div>
    
    <div class="messages">
        {messages_html}
    </div>
    
    <div class="footer">
        Generated by NEXUS Chat to PDF Converter<br>
        {date}
    </div>
</body>
</html>
"""
    
    messages_html = ""
    for i, (role, content) in enumerate(messages, 1):
        # HTML escape (basit versiyon)
        content = content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        
        # Code blocks'u highlight et
        if '```' in content:
            parts = content.split('```')
            for j in range(1, len(parts), 2):
                if j < len(parts):
                    # Code block içeriği
                    code_content = parts[j]
                    # İlk satırı (dil) ayır
                    lines = code_content.split('\n', 1)
                    if len(lines) > 1:
                        code_content = lines[1]
                    parts[j] = f'<pre>{code_content}</pre>'
            content = ''.join(parts)
        
        messages_html += f"""
        <div class="message {role}">
            <div class="message-header">
                {role.upper()} (Mesaj #{i})
            </div>
            <div class="message-content">
                {content}
            </div>
        </div>
        """
    
    html_content = html_template.format(
        title=title,
        date=datetime.now().strftime("%d %B %Y, %H:%M"),
        message_count=len(messages),
        messages_html=messages_html
    )
    
    return html_content


def manual_entry_mode():
    """
    Manuel mesaj girişi modu
    Kullanıcı mesajları elle girer
    """
    
    print("=" * 70)
    print("📝 CHAT TO PDF CONVERTER - MANUEL MOD")
    print("=" * 70)
    print("\nMesajları tek tek girin.")
    print("Her mesaj için:")
    print("  1. Role yazın (user veya assistant)")
    print("  2. İçeriği yazın (çok satırlı olabilir)")
    print("  3. Boş satır + 'END' yazın")
    print("\nTüm mesajlar bitince 'DONE' yazın.\n")
    
    messages = []
    
    while True:
        role = input("\nRole (user/assistant) veya DONE: ").strip().lower()
        
        if role == 'done':
            break
        
        if role not in ['user', 'assistant']:
            print("❌ Geçersiz role! 'user' veya 'assistant' yazın.")
            continue
        
        print(f"Mesaj içeriği (bitince 'END' yazın):")
        lines = []
        while True:
            line = input()
            if line.strip() == 'END':
                break
            lines.append(line)
        
        content = '\n'.join(lines)
        messages.append((role, content))
        print(f"✅ Eklendi: {len(messages)}. mesaj")
    
    return messages


def export_session():
    """Chat session'ı export et"""
    
    print("\n" + "=" * 70)
    print("🎯 NEXUS SESSION 2 - QUICK SUMMARY")
    print("=" * 70)
    
    # Önemli mesajları özetleyelim
    summary_messages = [
        ("user", """NEXUS Data Cleanroom projesine devam ediyoruz.
        
Session 1'de tamamlananlar:
- M1: Database Schema (6 SQL dosyası)
- M3: AI Mapping Engine (Heuristic + Embedding + LLM, 97.2 skor)
- SAP EBELN → po_id test başarılı (0.99 confidence)

Şimdi M5 ve M7'yi yapalım."""),
        
        ("assistant", """Mükemmel! M5 (Event Builder) ve M7 (XES Writer) yazıyorum.

M5 - Event Constructor:
- Logo purchase data'yı event log'a çevirir
- INTERIM_STATUSES'u parse eder
- Timestamp mapping yapar
- 18,100 event oluşturur

M7 - XES Writer:
- PM4Py, ProM, Celonis uyumlu
- XML formatında XES dosyası
- Trace ve event attributes
- Process mining hazır!"""),
        
        ("user", """Logo verisi analizi:
- 5,000 satır purchase order
- 20 kolon (5 yeni kolon eklendi)
- APPROVAL_DATETIME, SHIPMENT_DATETIME, DELIVERY_DATETIME
- APPROVED_BY, INTERIM_STATUSES
- Hiç null değer yok!"""),
        
        ("assistant", """Logo verisi MÜKEMMEl!

Analiz sonuçları:
✅ 20/20 kolon eşleşti (NEXUS M3, %100 başarı)
✅ Ortalama confidence: 0.972 (97.2/100)
✅ Event log: 18,100 event, 4,985 case, 5 activity
✅ Ortalama lead time: 17.9 gün
⚠️ Darboğaz: Sevkiyat → Teslim (10.6 gün)

Süreç akışı:
Talep Oluşturuldu → Onay Bekliyor → Onaylandı → Sevk Edildi → Teslim Edildi"""),
        
        ("user", """Full pipeline test yapalım!"""),
        
        ("assistant", """Full pipeline başarıyla çalıştı!

📊 Sonuçlar:
✅ 5,000 satır Logo CSV işlendi
✅ 18,100 event oluşturuldu
✅ Event log valid
✅ XES dosyası: 10.6 MB
✅ CSV dosyası: 2.1 MB

Dosyalar:
- logo_purchase_event_log.xes (ProM/Celonis/Disco'ya hazır)
- logo_purchase_event_log.csv (Excel'de görüntüle)
- event_constructor.py (src/event_builder/)
- xes_writer.py (src/storage/formats/)

NEXUS Modules Çalışıyor:
✅ M1: Database Schema
✅ M3: AI Mapping (97.2%)
✅ M5: Event Builder
✅ M7: XES Writer

Kalan (Next Session):
⏳ M2: Logo Connector
⏳ M4: Quality Checker
⏳ M6: Review Console

Progress: 70% Complete!"""),
        
        ("user", """Yedek aldık:
- nexus_backup_20241118_session2.zip (87 MB)
- Tüm kodlar güvende!

Bir sonraki oturumda M2, M4, M6'yı bitirip production-ready yapalım!"""),
    ]
    
    return summary_messages


# MAIN
if __name__ == "__main__":
    
    print("=" * 70)
    print("🎯 NEXUS CHAT TO PDF CONVERTER")
    print("=" * 70)
    
    # Session 2 özet mesajları
    messages = export_session()
    
    # HTML oluştur
    title = "NEXUS Session 2 - Event Builder & XES Export"
    html_content = create_html_from_messages(messages, title)
    
    # HTML dosyasına yaz
    html_path = '/mnt/user-data/outputs/nexus_session2_summary.html'
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"\n✅ HTML oluşturuldu: {html_path}")
    print(f"📊 Toplam mesaj: {len(messages)}")
    
    # Kullanım talimatları
    print("\n" + "=" * 70)
    print("📥 NASIL PDF'E ÇEVRİLİR?")
    print("=" * 70)
    print("""
1. HTML dosyasını indirin (aşağıdaki link)
2. Tarayıcıda açın (Chrome veya Safari)
3. Cmd/Ctrl + P → Print
4. "Save as PDF" seçin
5. Kaydedin!

Not: HTML güzel formatlanmış, direkt okunabilir!
""")
    
    print("\n✅ Script tamamlandı!")
